### ISSUE TITLE
Cannot set --quiet or --timeout

### ISSUE THREAD

**Issue by paulearley** [icemarkom/mffprober#1]
Cannot set --quiet or --timeout

**Program reports:**
flag provided but not defined: -quiet
Usage of prober:
  -exit-on-error
        Exit polling loop on error (default true)
  -host string
        Host to probe
  -interval int
        Polling interval in seconds (default 10)

**Comment by icemarkom** [comment]
I think you need to either recompile it, or pull new version from GitHub.

**Comment by paulearley** [comment]
> I think you need to either recompile it, or pull new version from GitHub.
That did it. For some reason (operator error) the pull failed.
Running now. Will run all night.
